export const ADD_PRODUCT = "ADD_PRODUCT";
export const CURRENT_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS_REQUEST="FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE="FETCH_PRODUCTS_FAILURE";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const EDIT_PRODUCT="EDIT_PRODUCT";

