export const ADD_PRODUCT = "ADD_PRODUCT";
export const CURRENT_PRODUCT = "CURRENT_PRODUCT";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const CALCULATE_BILL = "CALCULATE_BILL";
export const COMPLETE_TRANSACTION = "COMPLETE_TRANSACTION";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";
export const COMPLETE_TRANSACTION_REQUEST = "COMPLETE_TRANSACTION_REQUEST";

export const FETCH_ALL_TRANSACTIONS_REQUEST='FETCH_ALL_TRANSACTIONS_REQUEST';
export const FETCH_ALL_TRANSACTIONS_SUCCESS='FETCH_ALL_TRANSACTIONS_SUCCESS';
export const FETCH_ALL_TRANSACTIONS_FAILURE='FETCH_ALL_TRANSACTIONS_FAILURE';
